services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: comments/app
        restart: always
        ports:
            # - ${APP_PORT:-80}:80
            # - 443:443
            - 8000:80
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/sites-available/default
            - ./docker/nginx/snippets:/etc/nginx/snippets
            - ./docker/ssl/certificates/:/etc/ssl/certificates
            - ./docker/ssl/keys/:/etc/ssl/keys
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./src:/app
            # - ./docker/app/php.ini:/usr/local/etc/php/php.ini
            - ./docker/app/entrypoint.sh:/usr/local/bin/entrypoint.sh
        networks:
            - default
        depends_on:
            - database
  
    cron:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: comments/app
        restart: always
        command: crond -f
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/sites-available/default
            - ./docker/nginx/snippets:/etc/nginx/snippets
            - ./docker/ssl/certificates/:/etc/ssl/certificates
            - ./docker/ssl/keys/:/etc/ssl/keys
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./src:/app
            - ./docker/cron/crontab:/var/spool/cron/crontabs/root
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
            - ./docker/app/entrypoint.sh:/usr/local/bin/entrypoint.sh
        networks:
            - default
        depends_on:
            - database
  
    memcached:
        image: memcached:alpine
        restart: always
        networks:
            - default
  
    mail:
        image: mailhog/mailhog
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - default

    database:
        image: mysql
        restart: always
        volumes:
            - ./data/db-data:/var/lib/mysql
        command: mysqld --explicit_defaults_for_timestamp
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-secret}
            MYSQL_DATABASE: ${DATABASE_DATABASE:-drupal}
            MYSQL_USER: ${DATABASE_USERNAME:-drupal}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD:-drupal}
        networks:
            - default

    websocket:
        image: centrifugo/centrifugo:v5
        command: centrifugo -c config.json
        volumes:
            - ./docker/websocket:/centrifugo 
        networks:
            - default
        ulimits:
            nofile: 262144

networks:
    default:
        driver: overlay
        attachable: true
